[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "xense_franka"
version = "0.2.0"
description = "Xense SDK for Franka robot control using asyncio."
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}

authors = [
    {name = "dyl"}
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "pylibfranka",
    "ruckig",
    "numpy",
    "scipy",
    "tqdm",
    "requests",
]

[project.urls]
Homepage = "https://github.com/xensedyl/xense_franka"
Repository = "https://github.com/xensedyl/xense_franka"
